### ISSUE TITLE
Feature request: batch autofilling

### ISSUE THREAD

**Issue by axoxolotl** [interborough/mp3-metadata-autofiller#1]
First of all, I'd like to thank you for this script, it works flawlessly. 
Second, I have a feature request: batches. So, the option to add multiple files at the same time and have them done one after the other. 
The other thing I would be grateful to see would be more feedback when using the script. At this point, you add the file, and it just quits. There is no feedback if it was completed sucesfully. 
I have also noticed that it sometimes downloads multiple album artworks in different resolutions, and defaults to the one with the lowest resolution. 
Thank you :)

**Comment by interborough** [comment]
Hi!

Thank you for the kind words - I appreciate it. I'm glad that someone besides myself was able to use and benefit from this script. 

Regarding the issues that you presented: 
1. Multiple file input is a great idea and I'll work on implementing it as soon as possible. 
2. More user feedback is also a great idea, and I'll add that in the future as well. To be honest, I was writing this code in an IDE, so I completely forgot that the terminal window would just auto-close itself after completing the script execution. There actually are some user feedback statements already in the code, but you just can't see them when running the script since the terminal window auto-closes, haha. Naturally I'll fix this as well.
3. As far as I know the maximum album art size available from the Spotify Web API is 640×640 pixels. Additionally, some songs only have smaller sizes than that available. I'm pretty sure that the script should be selecting the largest album art size available, but its just that the largest size available is pretty small. I agree that a larger album art size would be nicer, so I'll see if there's another way around this.

Thanks again, and be sure to let me know if you have any other follow up information or questions.

**Comment by interborough** [comment]
Just pushed a new update to the script. It includes batch file processing and clearer user prompt information. Now the console window stays active until you press the "q" key, giving you as much time as you need to read the output.

Because of this, however, I had to add one more dependency. The Python keyboard library is now required for this script to work, and you can install it with the following command: pip install keyboard

Also, don't forget to re-add your personal client_id and client_secret values to this new script before testing it. 

I did not address the album art issue yet, since I haven't gotten a chance to see if it is simply a limitation of the Spotify API. 

Let me know if you have any issues with this new version!

**Comment by interborough** [comment]
Hello again! 

It seems the 640x640 album art size is simply a limitation of the Spotify API. 

To get around this, I added an alternate script - autofiller_sacad.py - that allows for custom album art sizes. Please see the updated readme for more information.

With that, I'll mark this issue as closed, but feel free to open another if you have any more problems or suggestions.

Thanks again for using this script!
